declare const styles: {
  readonly shell: string;
  readonly header: string;
  readonly brand: string;
  readonly brandAccent: string;
  readonly nav: string;
  readonly navLink: string;
  readonly navLinkActive: string;
  readonly main: string;
  readonly accountChip: string;
  readonly accountChipActive: string;
  readonly accountChipAvatar: string;
  readonly accountChipImg: string;
  readonly accountChipName: string;
  readonly decksMenu: string;
  readonly decksTrigger: string;
  readonly chevron: string;
  readonly chevronOpen: string;
  readonly decksDropdown: string;
  readonly decksItem: string;
  readonly decksItemActive: string;
};
export default styles;
