declare const styles: {
  readonly frame: string;
  readonly frameMulti: string;
  readonly frameBoth: string;
  readonly frameBothStack: string;
  readonly frameStackTall: string;
  readonly frameModalSlots: string;
  readonly frameTilt: string;
  readonly frameTiltActive: string;
  readonly tiltGlare: string;
  readonly faceObject: string;
  readonly faceSlot: string;
  readonly image: string;
  readonly both: string;
  readonly bothStack: string;
  readonly imageHalf: string;
  readonly controls: string;
  readonly controlBtn: string;
  readonly controlBtnActive: string;
  readonly faceBadge: string;
};
export default styles;
