declare const styles: {
  readonly page: string;
  readonly topBar: string;
  readonly backLink: string;
  readonly status: string;
  readonly statusError: string;
  readonly layout: string;
  readonly visual: string;
  readonly imageFrame: string;
  readonly info: string;
  readonly artCol: string;
  readonly badgeRow: string;
  readonly badge: string;
  readonly relatedSection: string;
  readonly relatedCard: string;
  readonly relatedTitle: string;
  readonly relatedBody: string;
  readonly relatedLink: string;
  readonly relatedSoon: string;
};
export default styles;
