declare const styles: {
  readonly landing: string;
  readonly glow: string;
  readonly hero: string;
  readonly eyebrow: string;
  readonly title: string;
  readonly titleAccent: string;
  readonly subtitle: string;
  readonly actions: string;
  readonly card: string;
  readonly cardMark: string;
  readonly cardTitle: string;
  readonly cardDesc: string;
  readonly cardCta: string;
  readonly accountPanel: string;
  readonly accountPanelHeader: string;
  readonly accountPanelLabel: string;
  readonly accountPanelName: string;
  readonly accountPanelEmail: string;
  readonly accountPanelLink: string;
  readonly footer: string;
  readonly themeBar: string;
  readonly themeLabel: string;
  readonly themeBtn: string;
  readonly themeBtnActive: string;
};
export default styles;
